---
# Install Boto and setup Creds
- name: Install boto3
  pip: name=boto3 state=latest

- file: path="/{{ aws_user_home }}/.aws" state=directory mode=0755 owner={{ aws_user }} group={{ aws_user }}

- name: Copy AWS Credentials
  template: src=aws.config.j2 dest="/{{ aws_user_home }}/.aws/config" owner={{ aws_user }} group={{ aws_user }} mode=600
- name:
  template: src=aws.credentials.j2 dest="/{{ aws_user_home }}/.aws/credentials" owner={{ aws_user }} group={{ aws_user }} mode=600
